#include "../Headers.h"
#include "../Parser/Ingresar.cpp"
#include "../Parser/Verificar.cpp"

#include "../Comandos/Cat.cpp"
#include "../Comandos/Chgrp.cpp"
#include "../Comandos/Chmod.cpp"
#include "../Comandos/Chown.cpp"
#include "../Comandos/Cp.cpp"
#include "../Comandos/Edit.cpp"
#include "../Comandos/Exec.cpp"
#include "../Comandos/Fdisk.cpp"
#include "../Comandos/Find.cpp"
#include "../Comandos/Login.cpp"
#include "../Comandos/Logout.cpp"
#include "../Comandos/Mkdir.cpp"
#include "../Comandos/Mkdisk.cpp"
#include "../Comandos/Mkfile.cpp"
#include "../Comandos/Mkfs.cpp"
#include "../Comandos/Mkgrp.cpp"
#include "../Comandos/Mkusr.cpp"
#include "../Comandos/Mount.cpp"
#include "../Comandos/Mv.cpp"
#include "../Comandos/Pause.cpp"
#include "../Comandos/Rem.cpp"
#include "../Comandos/Ren.cpp"
#include "../Comandos/Rep.cpp"
#include "../Comandos/Rmdisk.cpp"
#include "../Comandos/Rmgrp.cpp"
#include "../Comandos/Rmusr.cpp"
#include "../Comandos/Unmount.cpp"

Cat cat;
Chgrp chgrp;
Chmod chmod;
Chown chown;
Cp cp;
Edit edit;
Exec exec;
Fdisk fdisk;
Find find_;
Login login;
Logout logout;
Mkdir mkdir;
Mkdisk mkdisk;
Mkfile mkfile;
Mkfs mkfs;
Mkgrp mkgrp;
Mkusr mkusr;
Mount mount;
Mv mv;
Pause pause;
Rem rem;
Ren ren;
Rep rep;
Rmdisk rmdisk;
Rmgrp rmgrp;
Rmusr rmusr;
Unmount unmount;